grails/todo/grails-app/domain/es/ua/expertojava/todo/Category.groovy
package es.ua.expertojava.todo

class Category {

    String name
    String description

    static searchable = true

    static hasMany = [todos:Todo]

    static constraints = {
        name(blank:false)
        description(blank:true, nullable:true, maxSize:1000)
    }

    String toString(){
        name
    }
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/RequestMap.groovy
package es.ua.expertojava.todo

import org.springframework.http.HttpMethod

class RequestMap {

	String url
	String configAttribute
	HttpMethod httpMethod

	static mapping = {
		cache true
	}

	static constraints = {
		url blank: false, unique: 'httpMethod'
		configAttribute blank: false
		httpMethod nullable: true
	}
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Role.groovy
package es.ua.expertojava.todo

class Role {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Todo.groovy
package es.ua.expertojava.todo

class Todo {
    String title
    String description
    Date date
    Date reminderDate
    String url
    Category category
    Boolean finalizado
    Date dateCreated
    Date lastUpdated
    Date dateDone
    User user

    static searchable = [except: ['date', 'reminderDate']]

    static hasMany = [tags:Tag]
    static belongsTo = [Tag]

    static constraints = {
        title(blank:false)
        description(blank:true, nullable:true, maxSize:1000)
        reminderDate(nullable:true,
                validator: { val, obj ->
                    if (val && obj.date) {
                        return val.before(obj?.date)
                    }
                    return true
                }
        )
        url(nullable:true, url:true)
        category(nullable:true)
        finalizado(blank: false)
        dateDone(nullable: true)
    }

    String toString(){
        "title"
    }

}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/CategoryController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class CategoryController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def categoryService


    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Category.list(params), model:[categoryInstanceCount: Category.count()]
    }

    def show(Category categoryInstance) {
        respond categoryInstance
    }

    def create() {
        respond new Category(params)
    }

    @Transactional
    def save(Category categoryInstance) {
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'create'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'category.label', default: 'Category'), categoryInstance.name])
                redirect categoryInstance
            }
            '*' { respond categoryInstance, [status: CREATED] }
        }
    }

    def edit(Category categoryInstance) {
        respond categoryInstance
    }

    @Transactional
    def update(Category categoryInstance) {
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'edit'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.id])
                redirect categoryInstance
            }
            '*'{ respond categoryInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Category categoryInstance) {

        if (categoryInstance == null) {
            notFound()
            return
        }

        //categoryInstance.delete flush:true
        if(categoryInstance != null) {
            categoryService.removeCategory(categoryInstance)
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'category.label', default: 'Category'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/SearchableModController.groovy
/*
 * Copyright 2007 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package es.ua.expertojava.todo

import org.compass.core.engine.SearchEngineQueryParseException

/**
 * Basic web interface for Grails Searchable Plugin 
 *
 * @author Maurice Nicholson
 */
class SearchableModController {
    def searchableService
    def springSecurityService
    /**
     * Index page with search form and results
     */
    def index = {
        if (!params.q?.trim()) {
            return [:]
        }
        try {
            def currentUser = springSecurityService.getCurrentUser()
            def search =  [searchResult: searchableService.search(params.q, params)]

            ArrayList list = search.searchResult.results.clone()

            list.each{
                if(it instanceof Todo ){
                  if( !it.user.username.equals(currentUser.username)){
                      search.searchResult.results.remove(it)
                  }
                }
            }
            search.searchResult.totalResults = search.searchResult.results.size()
            return search
        } catch (SearchEngineQueryParseException ex) {
            return [parseException: true]
        }
    }

    /**
     * Perform a bulk index of every searchable object in the database
     */
    def indexAll = {
        Thread.start {
            searchableService.index()
        }
        render("bulk index started in a background thread")
    }

    /**
     * Perform a bulk index of every searchable object in the database
     */
    def unindexAll = {
        searchableService.unindex()
        render("unindexAll done")
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/TagController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class TagController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Tag.list(params), model:[tagInstanceCount: Tag.count()]
    }

    def show(Tag tagInstance) {
        respond tagInstance
    }

    def create() {
        respond new Tag(params)
    }

    @Transactional
    def save(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'create'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tag.label', default: 'Tag'), tagInstance.id])
                redirect tagInstance
            }
            '*' { respond tagInstance, [status: CREATED] }
        }
    }

    def edit(Tag tagInstance) {
        respond tagInstance
    }

    @Transactional
    def update(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'edit'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.id])
                redirect tagInstance
            }
            '*'{ respond tagInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Tag tagInstance) {

        if (tagInstance == null) {
            notFound()
            return
        }

        tagInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tag.label', default: 'Tag'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
    @Transactional
    def deletePrevio(Tag tagInstance) {
        respond tagInstance
    }

}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/TodoController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
@Secured(['ROLE_BASIC'])
@Transactional(readOnly = true)
class TodoController {
    def springSecurityService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def todoService
    @Secured(['ROLE_BASIC'])
    def index(Integer max) {
        def user = springSecurityService.currentUser
        params.max = Math.min(max ?: 10, 100)

        respond Todo.findAllByUser(user,params), model:[todoInstanceCount: Todo.countByUser(user,params)]
    }

    def listByCategory() {

        respond Category.list()
    }
    @Secured(['ROLE_ADMIN'])
    def showTodosByUser(){
      //  def user = springSecurityService.currentUser
        def user = User.findByUsername(params.username)
       respond Todo.findAllByUser(user)
    }

    def busquedaHorasPrevio() {
        def user = springSecurityService.currentUser
        respond  Todo.findAllByUser(user), model:[todoInstanceCount: Todo.countByUser(user)]
    }

    def lastTodosDone(Integer horas) {
        respond todoService.lastTodosDone(horas)
    }
    def listByCategoryResult(params) {
        def selectedCategories = params.seleccionados.collect{it.toLong()}

         respond todoService.listByCategory(Category.getAll(selectedCategories))
    }

    def show(Todo todoInstance) {
        respond todoInstance
    }

    def create() {
        def user = springSecurityService.currentUser
     //   def todo = new Todo(params)
        params.user = user
      //  todo.user=user
        respond new Todo(params)
    }

    @Transactional
    def save(Todo todoInstance) {
        def user = springSecurityService.currentUser
        if (todoInstance == null) {
            notFound()
            return
        }

        if (todoInstance.hasErrors()) {
            respond todoInstance.errors, view:'create'
            return
        }

        todoInstance.user=user
        //todoInstance.save flush:true
        todoInstance= todoService.saveTodo(todoInstance)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'todo.label', default: 'Todo'), todoInstance.id])
                redirect todoInstance
            }
            '*' { respond todoInstance, [status: CREATED] }
        }
    }

    def edit(Todo todoInstance) {
        respond todoInstance
    }

    @Transactional
    def update(Todo todoInstance) {
        if (todoInstance == null) {
            notFound()
            return
        }

        if (todoInstance.hasErrors()) {
            respond todoInstance.errors, view:'edit'
            return
        }

      //  todoInstance.save flush:true
        todoService.saveTodo(todoInstance)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Todo.label', default: 'Todo'), todoInstance.id])
                redirect todoInstance
            }
            '*'{ respond todoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Todo todoInstance) {

        if (todoInstance == null) {
            notFound()
            return
        }

        //todoInstance.delete flush:true
        todoService.removeTodo(todoInstance)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Todo.label', default: 'Todo'), todoInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'todo.label', default: 'Todo'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def listNextTodos(Integer days) {
        respond todoService.getNextTodos(days, params),
                model:[todoInstanceCount:
                               todoService.countNextTodos(days)],
                view:"index"
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/UserController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class UserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond userInstance
    }

    def create() {
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'create'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*' { respond userInstance, [status: CREATED] }
        }
    }

    def edit(User userInstance) {
        respond userInstance
    }

    @Transactional
    def update(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'edit'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/views/todo/index.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="listByCategory"><g:message code="default.listByCategory.label" default="Listado por Categorias" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="busquedaHorasPrevio"><g:message code="default.listByCategory.label" default="Listado por Horas" args="[entityName]" /></g:link></li>
				<li><g:link class="create" controller="searchableMod" action="index"><g:message code="default.buscador.label" default="Buscador"/></g:link></li>
			</ul>
		</div>
		<div id="list-todo" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />
					
						<%--<g:sortableColumn property="description" title="${message(code: 'todo.description.label', default: 'Description')}" />--%>
					
						<g:sortableColumn property="date" title="${message(code: 'todo.date.label', default: 'Date')}" />
					
						<%--<g:sortableColumn property="reminderDate" title="${message(code: 'todo.reminderDate.label', default: 'Reminder Date')}" />--%>
					
						<g:sortableColumn property="url" title="${message(code: 'todo.url.label', default: 'Url')}" />
					
						<th><g:message code="todo.category.label" default="Category" /></th>
						<g:sortableColumn property="finalizado" title="${message(code: 'todo.finalizado.label', default: 'finalizado')}" />
						<g:sortableColumn  property="title" title="${message(code: 'todo.url.label', default: 'Accion')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${todoInstanceList}" status="i" var="todoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${todoInstance.id}">${fieldValue(bean: todoInstance, field: "title")}</g:link></td>
					
						<%--<td>${fieldValue(bean: todoInstance, field: "description")}</td>--%>
					
						<td><g:formatDate date="${todoInstance.date}" /></td>
					
						<%-- <td><g:formatDate date="${todoInstance.reminderDate}" /></td>--%>
					
						<td>${fieldValue(bean: todoInstance, field: "url")}</td>
					
						<td>${fieldValue(bean: todoInstance, field: "category")}</td>
						<td><todo:printIconFromBoolean value="${todoInstance.finalizado}"/></td>
						<td>
							<g:form url="[resource:todoInstance, action:'delete']" method="DELETE">
								<fieldset class="buttons">
									<g:actionSubmit class="edit" action="edit" value=" " resource="${todoInstance}"/>
									<g:actionSubmit class="delete" action="delete" value=" " onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
								</fieldset>
							</g:form>
						<%--	<fieldset class="buttons">
								<g:submitButton name="edit" class="edit" />
								<g:submitButton name="delete" class="delete" />
							</fieldset>--%>

						</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${todoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails/todo/grails-app/views/todo/lastTodosDone.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="listByCategory"><g:message code="default.listByCategory.label" default="Listado por Categorias" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="busquedaHorasPrevio"><g:message code="default.listByCategory.label" default="Listado por Horas" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-todo" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />
					
						<%--<g:sortableColumn property="description" title="${message(code: 'todo.description.label', default: 'Description')}" />--%>
					
						<g:sortableColumn property="date" title="${message(code: 'todo.date.label', default: 'Date')}" />
					
						<%--<g:sortableColumn property="reminderDate" title="${message(code: 'todo.reminderDate.label', default: 'Reminder Date')}" />--%>
					
						<g:sortableColumn property="url" title="${message(code: 'todo.url.label', default: 'Url')}" />
					
						<th><g:message code="todo.category.label" default="Category" /></th>
						<g:sortableColumn property="finalizado" title="${message(code: 'todo.finalizado.label', default: 'finalizado')}" />
						<g:sortableColumn  property="title" title="${message(code: 'todo.url.label', default: 'Accion')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${todoInstanceList}" status="i" var="todoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${todoInstance.id}">${fieldValue(bean: todoInstance, field: "title")}</g:link></td>
					
						<%--<td>${fieldValue(bean: todoInstance, field: "description")}</td>--%>
					
						<td><g:formatDate date="${todoInstance.date}" /></td>
					
						<%-- <td><g:formatDate date="${todoInstance.reminderDate}" /></td>--%>
					
						<td>${fieldValue(bean: todoInstance, field: "url")}</td>
					
						<td>${fieldValue(bean: todoInstance, field: "category")}</td>
						<td><todo:printIconFromBoolean value="${todoInstance.finalizado}"/></td>
						<td>
							<g:form url="[resource:todoInstance, action:'delete']" method="DELETE">
								<fieldset class="buttons">
									<g:actionSubmit class="edit" action="edit" value=" " resource="${todoInstance}"/>
									<g:actionSubmit class="delete" action="delete" value=" " onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
								</fieldset>
							</g:form>
						<%--	<fieldset class="buttons">
								<g:submitButton name="edit" class="edit" />
								<g:submitButton name="delete" class="delete" />
							</fieldset>--%>

						</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${todoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails/todo/grails-app/views/todo/listByCategory.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
    </ul>
</div>
<div id="list-todo" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>


    <table>
        <thead>
        <tr>

            <g:sortableColumn property="name" title="${message(code: 'category.name.label', default: 'Name')}" />




        </tr>
        </thead>
        <tbody>
        <g:form url="[resource:todoInstance, action:'listByCategoryResult']" >

        <g:each in="${categoryInstanceList}" status="i" var="categoryInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">


                <td><g:checkBox name="seleccionados" value="${fieldValue(bean: categoryInstance, field: "id")}"/>
                ${fieldValue(bean: categoryInstance, field: "name")}
                </td>

                <%--	<td>${fieldValue(bean: categoryInstance, field: "description")}</td>--%>

            </tr>
        </g:each>
            <fieldset class="buttons">
                <g:actionSubmit class="button" action="listByCategoryResult" value="LISTADO"/>

            </fieldset>
        </g:form>
        </tbody>

    </table>



</div>
</body>
</html>

grails/todo/grails-app/views/todo/listByCategoryResult.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="listByCategory"><g:message code="default.listByCategory.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-todo" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />
					
						<%--<g:sortableColumn property="description" title="${message(code: 'todo.description.label', default: 'Description')}" />--%>
					
						<g:sortableColumn property="date" title="${message(code: 'todo.date.label', default: 'Date')}" />
					
						<%--<g:sortableColumn property="reminderDate" title="${message(code: 'todo.reminderDate.label', default: 'Reminder Date')}" />--%>
					
						<g:sortableColumn property="url" title="${message(code: 'todo.url.label', default: 'Url')}" />
					
						<th><g:message code="todo.category.label" default="Category" /></th>
						<g:sortableColumn property="finalizado" title="${message(code: 'todo.finalizado.label', default: 'finalizado')}" />
						<g:sortableColumn  property="title" title="${message(code: 'todo.url.label', default: 'Accion')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${todoInstanceList}" status="i" var="todoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${todoInstance.id}">${fieldValue(bean: todoInstance, field: "title")}</g:link></td>
					
						<%--<td>${fieldValue(bean: todoInstance, field: "description")}</td>--%>
					
						<td><g:formatDate date="${todoInstance.date}" /></td>
					
						<%-- <td><g:formatDate date="${todoInstance.reminderDate}" /></td>--%>
					
						<td>${fieldValue(bean: todoInstance, field: "url")}</td>
					
						<td>${fieldValue(bean: todoInstance, field: "category")}</td>
						<td><todo:printIconFromBoolean value="${todoInstance.finalizado}"/></td>
						<td>
							<g:form url="[resource:todoInstance, action:'delete']" method="DELETE">
								<fieldset class="buttons">
									<g:actionSubmit class="edit" action="edit" value=" " resource="${todoInstance}"/>
									<g:actionSubmit class="delete" action="delete" value=" " onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
								</fieldset>
							</g:form>
						<%--	<fieldset class="buttons">
								<g:submitButton name="edit" class="edit" />
								<g:submitButton name="delete" class="delete" />
							</fieldset>--%>

						</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${todoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>